User tinyproxy
Group tinyproxy

Port 8888
Listen 127.0.0.1

Timeout 600
MaxClients 100

Filter "/etc/tinyproxy/allowlist"
FilterDefaultDeny Yes
FilterURLs Off
FilterCaseSensitive Off
FilterType ere

ConnectPort 443
ConnectPort 80

LogFile "/var/log/tinyproxy/tinyproxy.log"
LogLevel Info

DisableViaHeader Yes
